#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl10, OnOffButton,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)

bool bMotorsDisabled  = true;
bool bClickInProgress = false;

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Triple Sensor Line Track for Distance
This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface
for 5 wheel rotations. There is a two second pause at the beginning of the program.

The threshold variable defined in this program may need to be changed for the line/surface your
robot is tracking and the lighting conditions.

Robot Model(s): Squarebot

[I/O Port]          [Name]                   [Type]                [Description]
Motor Port 2        rightMotor               VEX Motor             Right side motor
Motor Port 3        leftMotor                VEX Motor             Left side motor
Analog Port 1       lineFollowerLEFT         VEX Line Follower     Front-left, facing down
Analog Port 2       lineFollowerCENTER       VEX Line Follower     Front-center, facing down
Analog Port 3       lineFollowerRIGHT        VEX Line Follower     Front-right, facing down
Digital Port 1      rightEncoder             VEX Shaft Encoder     Right Side encoder
Digital Port 3      leftEncoder              VEX Shaft Encoder     Left side encoder

*To run this sample program on Swervebot, be sure to Reverse Motor Port 3 in the Motors and Sensors
 Setup, and to make sure that Motor Port 2 is NOT Reversed.
----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

//Fall fyrir neiadarhnappinn
void processButton()
{
  if (bClickInProgress)
  {
    if (SensorValue[OnOffButton])
      bClickInProgress = false;
  }
  else
  {
    if (!SensorValue[OnOffButton])
    {
      bMotorsDisabled = !bMotorsDisabled;
      bClickInProgress = true;
    }
  }
}

task main()
{
  wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

  SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;

  int throskuldur = 2048;    /* maelir ljosin a milli dokt og ljost   */

  int halfurHradi = 63;

  while(SensorValue[rightEncoder] < 4*throskuldur)
{
    // Syna stodu a ollum sensorum - - - - - - - - - - - - - - - - - - - - - -/
    displayLCDCenteredString(0, "LEFT  CNTR  RGHT");
    displayLCDNumber(1, 0, SensorValue(leftLineFollower), 4);
    displayLCDNumber(1, 6, SensorValue(centerLineFollower), 4);
    displayLCDNumber(1, 12, SensorValue(rightLineFollower), 4);
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -/
    //Ytt er a neidarhnappinn
     processButton();

    // haegri sensor ser svarta linu :
    if(SensorValue(rightLineFollower) > throskuldur)
    {
      // snuid til haegri:
      motor[leftMotor]  = halfurHradi;
      motor[rightMotor] = 0;
    }
    // thegr midju sensor ser svart:
    if(SensorValue(centerLineFollower) > throskuldur)
    {
      // keyrir beint afram
      motor[leftMotor]  = halfurHradi;
      motor[rightMotor] = halfurHradi;
    }
    // vinstri sensor ser svarta linu:
    if(SensorValue(leftLineFollower) > throskuldur)
    {
      // snuid til vinstri:
      motor[leftMotor]  = 0;
      motor[rightMotor] = halfurHradi;
    }
    // slokkt a motornum ef buid ad yta a neydarhnappinn
    if (bMotorsDisabled)
    {
      motor[leftMotor]  = 0;
      motor[rightMotor] = 0;
    }



  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
