#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*----------------------------------------------------------------------------------------------------*\
|*                                 - Moving Straight with Encoders -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program implements a self-straightening algorithm that provides a higher power level to the  *|
|*  motor that has traveled less, determined by comparing the values of the two encoders.             *|
|*  There is a 2 second pause at the beginning of the program.                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightMotor        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftMotor         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
const int BASEDIST = 1000;
void drive(int dist, int dir){
	while(abs(nMotorEncoder[rightMotor])<dist)		// Creates an infinite loop, since "true" always evaluates to true
	{
		if(abs(nMotorEncoder[rightMotor]) == nMotorEncoder[leftMotor]) // If rightMotor has counted the same amount as leftMotor:
		{
			// Move Forward
			motor[rightMotor] = 80*dir;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80*dir;		    // Left Motor is run at power level 80
		}
		else if(abs(nMotorEncoder[rightMotor]) > nMotorEncoder[leftMotor])	// If rightMotor has counted more encoder counts
		{
			// Turn slightly right
			motor[rightMotor] = 60*dir;		    // Right Motor is run at power level 60
			motor[leftMotor]  = 80*dir;		    // Left Motor is run at power level 80
		}
		else	// Only runs if leftMotor has counted more encoder counts
		{
			// Turn slightly left
			motor[rightMotor] = 80*dir;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 60*dir;		    // Left Motor is run at power level 60
		}
	}
}
task main()
{
	wait1Msec(2000);							// Robot waits for 2000 milliseconds before executing program

	nMotorEncoder[rightMotor] = 0;	  // Set the encoder so that it starts counting at 0
	nMotorEncoder[leftMotor]  = 0;	  // Set the encoder so that it starts counting at 0

	for(int i = 1; i<6; i++){
		drive(BASEDIST*i,1);

		drive(BASEDIST*i,1);

	}
}
	//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
